CC = gcc
CC_FLAGS = -Wall -g
CC_TEST_FLAGS = -Isrc -Ivendor/acutest/include -Itests
NASM = nasm
OBJCOPY = objcopy

0x864_SOURCES = \
	src/harness.c \
	src/0x864.c.o \
	src/0x864.h \
	src/0x864.s.o

DEMO_SOURCES = $(wildcard tests/demos/*.s)
DEMO_0x864_OBJECTS = $(DEMO_SOURCES:.s=.0x864.o)
DEMO_0x864_TEXT_BINARIES = $(DEMO_SOURCES:.s=.0x864.text.bin)
DEMO_NASM_OBJECTS = $(DEMO_SOURCES:.s=.nasm.o)
DEMO_NASM_TEXT_BINARIES = $(DEMO_SOURCES:.s=.nasm.text.bin)

UNIT_TEST_SOURCES = \
	tests/unit_test_suite.c \
	tests/assembler.h \
	tests/assembler.o \
	tests/elf64.h \
	tests/elf64.o \
	tests/parser.h \
	tests/parser.o \
	tests/utils.h \
	tests/utils.o \
	src/0x864.c.o \
	src/0x864.h \
	src/0x864.s.o

all: src/0x864

clean:
	@rm -rf \
		src/0x864 \
		src/*.o \
		tests/*.o \
		tests/unit_test_suite \
		tests/demos/*.o \
		tests/demos/*.bin

test: test-unit test-binary

test-binary: $(DEMO_0x864_OBJECTS) \
		$(DEMO_0x864_TEXT_BINARIES) \
		$(DEMO_NASM_OBJECTS) \
		$(DEMO_NASM_TEXT_BINARIES)
	@printf '\e[1m>> Running Binary Test suite ...\e[0m\n'
	@./tests/demos/compare_binaries.sh $(DEMO_SOURCES)

test-unit: tests/unit_test_suite
	@printf '\e[1m>> Running Unit Test suite ...\e[0m\n'
	@./tests/unit_test_suite

src/0x864: $(0x864_SOURCES)
	@$(CC) $(CC_FLAGS) -o src/0x864 src/harness.c src/0x864.c.o src/0x864.s.o

src/%.c.o: src/%.c
	@$(CC) $(CC_FLAGS) -c -o $@ $<

src/%.s.o: src/%.s
	@$(NASM) -felf64 -o $@ $<

tests/demos/%.0x864.o: tests/demos/%.s src/0x864
	@./src/0x864 -felf64 -o $@ $< > /dev/null

tests/demos/%.0x864.text.bin: tests/demos/%.s src/0x864
	@./src/0x864 -o $@ $< > /dev/null

tests/demos/%.nasm.o: tests/demos/%.s
	@$(NASM) -O1 -felf64 -o $@ $<

# Extract the text sections from the object files generated by nasm.
tests/demos/%.nasm.text.bin: tests/demos/%.nasm.o
	@$(OBJCOPY) -I elf64-little -j .text -O binary $< $@

tests/%.o: tests/%.c
	@$(CC) $(CC_FLAGS) $(CC_TEST_FLAGS) -DTEST_NO_MAIN -c -o $@ $<

tests/unit_test_suite: $(UNIT_TEST_SOURCES)
	@$(CC) \
		$(CC_FLAGS) \
		$(CC_TEST_FLAGS) \
		tests/unit_test_suite.c \
		src/0x864.c.o \
		src/0x864.s.o \
		tests/assembler.o \
		tests/elf64.o \
		tests/parser.o \
		tests/utils.o \
		-o $@

.PHONY: all clean test test-binary test-unit
