CC = gcc
CC_FLAGS = -Wall -g
CC_TEST_FLAGS = -Isrc -Ivendor/acutest/include
NASM = nasm
OBJCOPY = objcopy

DEMO_SOURCES = $(wildcard tests/demos/*.s)
DEMO_0x864_TEXT_BINARIES = $(DEMO_SOURCES:.s=.0x864.text.bin)
DEMO_NASM_OBJECTS = $(DEMO_SOURCES:.s=.nasm.o)
DEMO_NASM_TEXT_BINARIES = $(DEMO_SOURCES:.s=.nasm.text.bin)

all: src/0x864

clean:
	@rm -rf \
		src/0x864 \
		src/0x864.o \
		tests/test \
		tests/demos/*.o \
		tests/demos/*.bin

test: test-unit test-binary

test-binary: $(DEMO_0x864_TEXT_BINARIES) \
		$(DEMO_NASM_OBJECTS) \
		$(DEMO_NASM_TEXT_BINARIES)
	@printf '\e[1m>> Running Binary Test suite ...\e[0m\n'
	@./tests/demos/compare_binaries.sh $(DEMO_SOURCES)

test-unit: tests/test
	@printf '\e[1m>> Running Unit Test suite ...\e[0m\n'
	@./tests/test

src/0x864: src/harness.c src/0x864.o
	@$(CC) $(CC_FLAGS) src/harness.c src/0x864.o -o src/0x864

src/0x864.o: src/0x864.s
	@$(NASM) -felf64 src/0x864.s -o src/0x864.o

tests/demos/%.0x864.text.bin: tests/demos/%.s src/0x864
	@./src/0x864 $< -o $@ > /dev/null

tests/demos/%.nasm.o: tests/demos/%.s
	@$(NASM) -felf64 $< -o $@

# Extract the text sections from the object files generated by nasm.
tests/demos/%.nasm.text.bin: tests/demos/%.nasm.o
	@$(OBJCOPY) -I elf64-little -j .text -O binary $< $@

tests/test: src/0x864
	@$(CC) $(CC_FLAGS) $(CC_TEST_FLAGS) tests/parser.c src/0x864.o -o tests/test

.PHONY: all clean test test-binary test-unit
