---
when:
    branch: "main"
    event: "push"
steps:
    - name: "Fix permissions for rootless containers"
      image: "git.kalehmann.de/infrastructure/dockerimages/bash:latest"
      commands:
          - "chown -R 1000:1000 ."
    - name: "Generate documentation"
      image: "git.kalehmann.de/infrastructure/dockerimages/doxygen:latest"
      commands:
          - "doxygen"
      depends_on:
          - "Fix permissions for rootless containers"
    - name: "Publish documentation"
      image: "git.kalehmann.de/infrastructure/dockerimages/lftp:latest"
      commands:
          - 'lftp -e "
                 set ftp:ssl-force true;
                 set ssl:verify-certificate yes;
                 open -u $${USER},$${PASSWORD} $${SERVER};
                 mirror
                     --reverse
                     --delete
                     $(pwd)/_html
                     0x864;
                 exit;"'
      environment:
          USER:
              from_secret: "ftp_user"
          PASSWORD:
              from_secret: "ftp_password"
          SERVER:
              from_secret: "ftp_server"
      depends_on:
          - "Generate documentation"
depends_on:
    - "selfhosting-elf"
...
