---
when:
    event: "push"
steps:
    - name: "Fix permissions for rootless containers"
      image: "git.kalehmann.de/infrastructure/dockerimages/bash:latest"
      commands:
          - "chown -R 1000:1000 ."
    - name: "Build"
      image: "git.kalehmann.de/karsten/0x864:latest"
      commands:
          - "make"
      depends_on:
          - "Fix permissions for rootless containers"
    - name: "Run tests"
      image: "git.kalehmann.de/karsten/0x864:latest"
      commands:
          - "make tests"
      depends_on:
          - "Build"
